# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0f73c440ab198580653c3dfc289c0576fa04cf1146098be66702593ed869873dcf1a9e45359c991da4d4987574d768f3697ad20bf3dcb4d9df864233de16840

test:
  secret_key_base: 3b233b300770d4cb9919e8a40e419bfb54a17d84e20c6feeedb9b8e61652a2d374f1481cdc8378071d808ed5a9342480c8671265e9006d39200e77c94c11d538

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
